/** Generated by itemis CREATE code generator. */

#ifndef VENDINGMACHINE_REQUIRED_H_
#define VENDINGMACHINE_REQUIRED_H_

#include "../src/sc_types.h"
#include "VendingMachine.h"


#ifdef __cplusplus
extern "C"
{
#endif 

/*! \file
This header defines prototypes for all functions that are required by the state machine implementation.

This state machine makes use of operations declared in the state machines interface or internal scopes. Thus the function prototypes:
- vendingMachine_leds
- vendingMachine_currentState
are defined.

These functions will be called during a 'run to completion step' (runCycle) of the statechart. 
There are some constraints that have to be considered for the implementation of these functions:
- never call the statechart API functions from within these functions.
- make sure that the execution time is as short as possible.

*/
extern void vendingMachine_leds( VendingMachine* handle, const sc_integer id);
extern void vendingMachine_currentState( VendingMachine* handle, const sc_integer state);




#ifdef __cplusplus
}
#endif 

#endif /* VENDINGMACHINE_REQUIRED_H_ */
